language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install --no-interaction --prefer-source --no-suggest

script:
  - vendor/bin/phpunit --process-isolation
